#!/usr/bin/env python3
#
# Copyright (C) Honey Bunny QT
# SPDX-License-Identifier: GPL-3.0-only
#
# Draws the pictures of the docs that are made of fields and boxes - the
# packet layouts of Hacking.md and Crypto.md, the lab of netns_testing.md -
# as SVG into docs/images/, in the colours of docs/images/overview.svg, for
# light and dark themes alike.  The layouts are written down below as
# fields at byte offsets, so a field that changes is changed in one place.
#
# usage: scripts/gen_doc_images.py [docs/images]

import os
import sys

FONT = 'system-ui, -apple-system, "Segoe UI", sans-serif'

STYLE = """
  <style>
    .box   {{ fill: #ffffff; stroke: #5c5c69; stroke-width: 1.2; }}
    .hi    {{ fill: #fdf0f6; stroke: #c2185b; stroke-width: 1.2; }}
    .opt   {{ fill: #f4f4f7; stroke: #9a9aa6; stroke-width: 1.2;
             stroke-dasharray: 5 3; }}
    .open  {{ fill: #ffffff; stroke: #5c5c69; stroke-width: 1.2;
             stroke-dasharray: 5 3; }}
    .nat   {{ fill: none; stroke: #9a9aa6; stroke-width: 1.2;
             stroke-dasharray: 5 4; }}
    .wire  {{ stroke: #5c5c69; stroke-width: 2; fill: none; }}
    .bar   {{ fill: #fdf0f6; stroke: #c2185b; stroke-width: 1.5; }}
    .label {{ font: 13px {font}; fill: #1e1e24; }}
    .title {{ font: 600 14px {font}; fill: #1e1e24; }}
    .small {{ font: 11px {font}; fill: #5c5c69; }}
    .xor   {{ font: 600 16px {font}; fill: #c2185b; }}
    @media (prefers-color-scheme: dark) {{
      .box   {{ fill: #23232b; stroke: #a3a3ae; }}
      .hi    {{ fill: #3a1f2c; stroke: #f06ba4; }}
      .opt   {{ fill: #1b1b22; stroke: #6f6f7b; }}
      .open  {{ fill: #23232b; stroke: #a3a3ae; }}
      .nat   {{ stroke: #6f6f7b; }}
      .wire  {{ stroke: #a3a3ae; }}
      .bar   {{ fill: #3a1f2c; stroke: #f06ba4; }}
      .label {{ fill: #ececf1; }}
      .title {{ fill: #ececf1; }}
      .small {{ fill: #a9a9b4; }}
      .xor   {{ fill: #f06ba4; }}
    }}
  </style>
""".format(font=FONT)


def esc(text):
    return (text.replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


def svg(width, height, title, desc, body):
    return """<svg xmlns="http://www.w3.org/2000/svg" \
viewBox="0 0 {w} {h}" width="{w}" height="{h}" \
role="img" aria-labelledby="title desc">
  <title id="title">{t}</title>
  <desc id="desc">{d}</desc>
  <!-- SPDX-License-Identifier: GPL-3.0-only -->
  <!-- SPDX-FileCopyrightText: Copyright Honey Bunny QT -->
  <!-- Generated by scripts/gen_doc_images.py: change it there -->{style}
{body}
</svg>
""".format(w=width, h=height, t=esc(title), d=esc(desc), style=STYLE,
           body="\n".join(body))


def text(x, y, s, cls="label", anchor="middle"):
    return ('  <text class="{}" x="{:g}" y="{:g}" text-anchor="{}">{}</text>'
            .format(cls, x, y, anchor, esc(s)))


def rect(x, y, w, h, cls, rx=0):
    return ('  <rect class="{}" x="{:g}" y="{:g}" width="{:g}" height="{:g}"'
            ' rx="{}"/>'.format(cls, x, y, w, h, rx))


def wire(x0, y0, x1, y1, extra=""):
    return '  <path class="wire" d="M {} {} L {} {}"{}/>'.format(
        x0, y0, x1, y1, extra)


# --- packet layouts: 32 bits a row, as in the RFCs ------------------------

BIT = 18            # px per bit
ROW = 34            # px per row of 4 bytes
LEFT = 44           # room for the byte offsets
TOP = 34            # room for the bit ruler


def lines_of(label):
    return label.split("\n")


def layout(fields, title, desc, first=0):
    """fields: (label, first byte, bytes, kind) with kind one of box, hi
    (what the picture is about), opt (only sometimes there) or open (goes
    on, the payload).  first: the byte offset of the first row."""
    end = max(start + (n or 4 - start % 4) for _, start, n, _ in fields)
    rows = (end - first + 3) // 4
    width = LEFT + 32 * BIT + 12
    height = TOP + rows * ROW + 10
    body = []

    # the ruler: bit numbers, and the bytes
    for b in range(32):
        body.append(text(LEFT + b * BIT + BIT / 2, TOP - 8, str(b % 10),
                         "small"))
    for row in range(rows):
        body.append(text(LEFT - 8, TOP + row * ROW + ROW / 2 + 4,
                         str(first + 4 * row), "small", "end"))

    for label, start, n, kind in fields:
        if not n:
            # open: to the end of its row
            n = 4 - (start % 4)
        stop = start + n
        segments = []           # (row, first byte in it, bytes in it)
        b = start
        while b < stop:
            row = (b - first) // 4
            row_end = first + 4 * (row + 1)
            take = min(stop, row_end) - b
            segments.append((row, (b - first) % 4, take))
            b += take
        # whole rows in a row of them make one block
        blocks = []
        for row, col, take in segments:
            last = blocks[-1] if blocks else None
            if (last and col == 0 and take == 4 and last[1] == 0
                    and last[3] == 4 and last[0] + last[2] == row):
                r0, c0, nrows, t0 = blocks[-1]
                blocks[-1] = (r0, c0, nrows + 1, t0)
            else:
                blocks.append((row, col, 1, take))
        biggest = max(range(len(blocks)),
                      key=lambda i: blocks[i][2] * blocks[i][3])
        for i, (row, col, nrows, take) in enumerate(blocks):
            x = LEFT + col * 8 * BIT
            y = TOP + row * ROW
            w = take * 8 * BIT
            h = nrows * ROW
            body.append(rect(x + 1, y + 1, w - 2, h - 2, kind, 3))
            if i == biggest:
                lines = lines_of(label)
                y0 = y + h / 2 - (len(lines) - 1) * 8 + 4
                for k, line in enumerate(lines):
                    body.append(text(x + w / 2, y0 + 16 * k, line,
                                     "label" if k == 0 else "small"))
            else:
                # the rest of a field that does not fit in its row
                name = lines_of(label)[0]
                body.append(text(x + w / 2, y + h / 2 + 4,
                                 name + " …" if i < biggest else "… " + name,
                                 "small"))
    return svg(width, height, title, desc, body)


PICTURES = {}

PICTURES["header-common.svg"] = layout([
    ("Version = 3", 0, 1, "box"),
    ("TTL", 1, 1, "box"),
    ("Flags\nincluding the message type", 2, 2, "box"),
    ("Community\n20 bytes, the name, padded with zeros", 4, 20, "box"),
], "The common part of every PDU's header",
    "Version, TTL and flags in the first four bytes, then the 20 bytes of "
    "the community's name.")

PACKET_REST = [
    ("Source MAC", 24, 6, "box"),
    ("Destination MAC", 30, 6, "box"),
    ("Socket flags\nIPv4 / IPv6, UDP / TCP", 36, 2, "opt"),
    ("Original UDP port", 38, 2, "opt"),
    ("Original IPv4 address\nwhen relayed: where it came from", 40, 4, "opt"),
    ("Compression", 44, 1, "box"),
    ("Transform", 45, 1, "box"),
    ("Payload: the frame, compressed\nand encrypted …", 46, 0, "open"),
]

PICTURES["packet.svg"] = layout([
    ("Version = 3", 0, 1, "box"),
    ("TTL", 1, 1, "box"),
    ("Flags", 2, 2, "box"),
    ("Community\n20 bytes", 4, 20, "box"),
] + PACKET_REST, "A PACKET, the PDU that carries a frame",
    "The common part, the source and destination MAC addresses, the "
    "socket a supernode adds when it relays the PACKET, the compression "
    "and transform ids, and the payload.")

PICTURES["packet-fields.svg"] = layout(
    PACKET_REST, "What follows the common part in a PACKET",
    "The MAC addresses, the socket a supernode adds, the compression and "
    "transform ids, and the payload.", first=24)

PICTURES["packet-ipv6-tail.svg"] = layout([
    ("Socket flags (IPv6)", 36, 2, "opt"),
    ("Original UDP port", 38, 2, "opt"),
    ("Original IPv6 address\n16 bytes", 40, 16, "opt"),
    ("Compression", 56, 1, "box"),
    ("Transform", 57, 1, "box"),
    ("Payload …", 58, 0, "open"),
], "The end of a PACKET relayed from an IPv6 address",
    "Socket flags and port, the 16 bytes of the IPv6 address, then the "
    "compression and transform ids and the payload.", first=36)

PICTURES["header-encryption-order.svg"] = layout([
    ("Community\nits first 20 bytes come first", 0, 20, "box"),
    ("Version = 3", 20, 1, "hi"),
    ("TTL", 21, 1, "hi"),
    ("Flags", 22, 2, "hi"),
], "The common part, reordered for header encryption",
    "The community's 20 bytes first, then the version, TTL and flags, "
    "moved from the first row to the sixth.")

PICTURES["header-encryption-iv.svg"] = layout([
    ("IV\n128 bits, from the checksum and the time stamp", 0, 16, "hi"),
    ("Magic \"n2\" = 0x6E32", 16, 2, "box"),
    ("Header length", 18, 2, "box"),
    ("Version = 3", 20, 1, "box"),
    ("TTL", 21, 1, "box"),
    ("Flags", 22, 2, "box"),
], "The common part with header encryption",
    "The first 16 bytes hold the IV, then the magic number n2 and the "
    "header length, then version, TTL and flags; encrypted from byte 16 on.")


def pre_iv():
    """The 128-bit pre-IV: checksum XOR time stamp, and 32 random bits"""
    px = 6                      # px per bit, 128 bits across
    left, top, row, gap = 20, 34, 40, 24
    width = left + 128 * px + 20
    height = top + 2 * row + gap + 36
    body = []
    for b in (0, 32, 64, 96, 127):
        body.append(text(left + b * px + (px / 2 if b == 127 else 0), top - 10,
                         str(b), "small", "middle"))

    def cell(b0, bits, r, label, cls="box", tall=False, first="label"):
        x = left + b0 * px
        y = top + r * (row + gap)
        h = 2 * row + gap if tall else row
        body.append(rect(x + 1, y + 1, bits * px - 2, h - 2, cls, 3))
        lines = lines_of(label)
        y0 = y + h / 2 - (len(lines) - 1) * 7 + 4
        for k, line in enumerate(lines):
            body.append(text(x + bits * px / 2, y0 + 14 * k, line,
                             first if k == 0 else "small"))

    cell(0, 64, 0, "64-bit checksum of the whole packet", "hi")
    cell(64, 32, 0, "0x00")
    cell(0, 32, 1, "0x00")
    cell(32, 52, 1, "52-bit time stamp, µs", "hi")
    cell(84, 8, 1, "counter", first="small")
    cell(92, 4, 1, "F")
    cell(96, 32, 0, "32 pseudo-\nrandom bits", "box", tall=True)
    body.append(text(left + 48 * px, top + row + gap / 2 + 6, "XOR", "xor"))
    body.append(text(left + 64 * px, top + 2 * row + gap + 26,
                     "the two rows exclusive-ored, the random bits next to "
                     "them: then one SPECK block step makes the IV",
                     "small"))
    return svg(width, height, "The 128-bit pre-IV of header encryption",
               "The checksum, exclusive-ored with the time stamp, its counter "
               "and flags, next to 32 pseudo-random bits.", body)


PICTURES["header-encryption-preiv.svg"] = pre_iv()


def netns_lab():
    """The lab of the netns scenarios"""
    w, h = 720, 330
    body = []
    bar_y = 120
    body.append(rect(30, bar_y, 660, 30, "bar", 8))
    body.append(text(360, bar_y + 20, '"internet" 203.0.113.0/24', "title"))

    def node(cx, y, title, sub, cls="box"):
        body.append(rect(cx - 70, y, 140, 50, cls, 8))
        body.append(text(cx, y + 22, title, "title"))
        body.append(text(cx, y + 39, sub, "small"))

    # the federated supernodes, above the bar
    for cx, name, addr in ((140, "sn1", ".1:7654"), (320, "sn2", ".2:7654")):
        body.append(wire(cx, 80, cx, bar_y))
        node(cx, 30, name, "supernode " + addr)
    body.append(wire(210, 55, 250, 55, ' stroke-dasharray="4 3"'))
    body.append(text(230, 20, "federated", "small"))

    # the edges without NAT
    body.append(wire(560, 80, 560, bar_y))
    node(560, 30, "public edges", "at .101 and up", "opt")

    # the sites: a router with its NAT, the edge behind it
    for cx, site, wan, ip in ((200, "a", ".11", "10.99.0.1/24"),
                              (520, "b", ".12", "10.99.0.2/24")):
        body.append(rect(cx - 110, 175, 220, 140, "nat", 12))
        body.append(text(cx - 98, 192, "site " + site, "small", "start"))
        body.append(wire(cx, bar_y + 30, cx, 200))
        node(cx, 200, "router " + site, "NAT, wan " + wan)
        body.append(wire(cx, 250, cx, 260))
        node(cx, 260, "edge " + site, ip, "hi")
    return svg(w, h, "The lab of the netns scenarios",
               "Two federated supernodes and the routers of two sites on one "
               "bridge, the internet; behind each router, with its kind of "
               "NAT, an edge.", body)


PICTURES["netns-lab.svg"] = netns_lab()


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "docs", "images")
    os.makedirs(out, exist_ok=True)
    for name, content in sorted(PICTURES.items()):
        with open(os.path.join(out, name), "w") as f:
            f.write(content)
        print(os.path.join(out, name))


if __name__ == "__main__":
    main()
