#!/usr/bin/env python3
#
# Copyright (C) Honey Bunny QT
# SPDX-License-Identifier: GPL-3.0-only
#
# Writes docs/configure/Options.md from what the program says about its own
# options ("n3n-edge help config"), so that the reference cannot drift from
# the code.
#
# usage: gen_options_md.py [path to n3n-edge] > docs/configure/Options.md

import re
import subprocess
import sys

# Defaults that depend on the machine the dump ran on
MACHINE = {
    ("connection", "description"): "the host name",
    ("daemon", "userid"): "the user n3n, else nobody",
    ("daemon", "groupid"): "the group of that user",
    ("supernode", "macaddr"): "a random one",
    ("supernode", "version"): "the version of the program",
}

# Values that stand for "not set"
UNSET = ("0.0.0.0/0", "0.0.0.0/24", "00:00:00:00:00:00", "")

HEADER = """\
<!--
SPDX-License-Identifier: GPL-3.0-only
SPDX-FileCopyrightText: Copyright Hamish Coleman
SPDX-FileCopyrightText: Copyright Honey Bunny QT
-->

# Configuration Options

<!-- Generated by scripts/gen_options_md.py from "n3n-edge help config"; do
not edit, run "make options" instead. -->

Every option the daemons know, by section, as the program itself describes
them.  An option goes into the configuration file in its section:

```
[connection]
bind = 7777
```

and on the command line as `-O section.option=value`, for example
`-O connection.bind=7777`.  See [Configuration Files](ConfigurationFiles.md).

The defaults given are those of an edge.  A supernode has a few others: it
binds to `[::]:7654` by default, and runs as the user that starts it.
Options given more than once (like `community.supernode` or
`supernode.community_regex`) add to a list.  A section with an instance name
in its header, like `[community home]`, is described in
[Communities](Communities.md).
"""


def parse(text):
    """[(section, help, [(option, desc, help, value or None)])]"""
    sections = []
    comments = []
    for line in text.split("\n"):
        line = line.rstrip()
        if line.startswith("####") or line.startswith("# Autogenerated"):
            continue
        m = re.match(r"^\[(\w+)\]$", line)
        if m:
            sections.append((m.group(1), " ".join(comments), []))
            comments = []
            continue
        if line.startswith("# "):
            comments.append(line[2:])
            continue
        if line == "#":
            continue
        m = re.match(r"^(#?)(\w+)=(.*)$", line)
        if m and sections:
            unset, name, value = m.groups()
            desc = comments[0] if comments else ""
            more = " ".join(comments[1:])
            # several values of a list are several lines: keep the first
            options = sections[-1][2]
            if not options or options[-1][0] != name:
                options.append((name, desc, more,
                                None if unset else value))
            comments = []
            continue
        if not line:
            continue
    return sections


def supernode_defaults(binary):
    """{option: value} of the [supernode] section of a supernode"""
    out = subprocess.run([binary, "debug", "config", "dump", "1"],
                         capture_output=True, text=True).stdout
    values = {}
    for section, _, options in parse(out):
        if section == "supernode":
            values = {name: value for name, _, _, value in options}
    return values


def main():
    edge = sys.argv[1] if len(sys.argv) > 1 else "apps/n3n-edge"
    supernode = sys.argv[2] if len(sys.argv) > 2 else "apps/n3n-supernode"
    out = subprocess.run([edge, "help", "config"], capture_output=True,
                         text=True).stdout
    sn_values = supernode_defaults(supernode)
    print(HEADER)
    for section, shelp, options in parse(out):
        if section == "supernode" and sn_values:
            options = [(n, d, m, sn_values.get(n)) for n, d, m, _ in options]
        print("## [{}]".format(section))
        print()
        if shelp:
            print(shelp)
            print()
        for name, desc, more, value in options:
            print("### {}.{}".format(section, name))
            print()
            if desc:
                end = "" if desc.endswith(".") else "."
                print(desc[0].upper() + desc[1:] + end)
                print()
            if more:
                print(more)
                print()
            machine = MACHINE.get((section, name))
            if machine:
                print("Default: {}.".format(machine))
                print()
            elif value is not None and value not in UNSET:
                print("Default: `{}`".format(value))
                print()


if __name__ == "__main__":
    main()
